### ISSUE TITLE
Using twig tags results in inline scripts blocked error

### ISSUE THREAD

**Issue by ghoot31** [akeneo/pim-docs#1454]
When trying to use a new module, that renders a template that uses <%- _.each(variable, function() ... %> to iterate over set parameter, i get information in the browser that csp blocked this inline script. I do everything as described in "How to add an action button or meta data to the product edit form" cookbook, and I never had this issue in akeneo 3.x whilst using such templates. Is there something I am doing wrong in 4.0 (or at all)? I could not find any information about what to do in regard to csp in such case.

**Comment by jmleroux** [comment]
If you want to use custom JS in your template, you must add the security nonce in this javascript tag, like in this file for example: https://github.com/akeneo/pim-community-dev/blob/4.0/src/Akeneo/Pim/Enrichment/Bundle/Resources/views/CategoryTree/_scripts.html.twig

Could you copy-paste your template to better see his structure?
