### ISSUE TITLE
Security issue: Installation manual instructs opening ports 3306 and 9200

### ISSUE THREAD

**Issue by pkraeutli** [akeneo/pim-docs#1600]
The installation manual here https://docs.akeneo.com/4.0/install_pim/manual/system_requirements/system_requirements.html
says to open MySQL and Elasticsearch ports:

![Screenshot 2021-03-24 at 14 00 28](https://user-images.githubusercontent.com/886082/112314406-4af71300-8ca9-11eb-9af9-4259c570284d.png)

If you run a standard Elasticsearch and you open port 9200, all your index data will be accessible from outside (possibly the internet). For MySQL (port 3306) it is a little less bad because you need the database credentials, but still it is not a good idea to open those ports.

Anyways, as far as I know these ports don't need to be open in order for Akeneo to work.

**Comment by jmleroux** [comment]
Fixed by removing the whole paragraph

**Comment by pkraeutli** [comment]
Thanks @jmleroux !
