### ISSUE TITLE
Settings ElasticSearch User and Password

### ISSUE THREAD

**Issue by thewasta** [akeneo/pim-docs#1646]
How can I set user and password for my ElasticSearch? Not SSL, my cluster is only using login system.

**Comment by pierrejolly** [comment]
Hello @thewasta your issue is more related to Elasticsearch you should try to contact them directly 🙂

**Comment by thewasta** [comment]
Hello, it's about Akeno. I guess I didn't express myself correctly. But got solution. On `.env.local` file have to write 
`APP_INDEX_HOSTS='elastic:changeme@192.168.1.142:9200'`
