### ISSUE TITLE
Product value validation link

### ISSUE THREAD

**Issue by Hocdoc** [akeneo/pim-docs#207]
In http://docs.akeneo.com/master/cookbook/catalog/product/validate.html at the last paragraph "Product value validation": 

Should `../custom_entity/creating_an_attribute_type` be a link to http://docs.akeneo.com/master/cookbook/catalog/product/validate.html ?

**Comment by a2xchip** [comment]
@Hocdoc is it still actual?

**Comment by Hocdoc** [comment]
Seems to be fixed.
