### ISSUE TITLE
Enhancements for contributors guide

### ISSUE THREAD

**Issue by a2xchip** [akeneo/pim-docs#274]
Hello guys! This week i was thinking about more things we may enhance in dev docs and found that there is nothing exact in code contribution section.

My proposition is to add more info about cloning fetching and pulling to dev repo. 

May be something like Sylius [did it](http://docs.sylius.org/en/latest/contributing/code/patches.html)?

**Comment by willy-ahva** [comment]
Hi @a2xchip !

Excellent idea ! I talked to @nidup for a doc about contributing something like 2 days ago.
What we pointed out was that contributors don't know what are conditions of acceptance of a PR in terms of if it's a bug or an enhancement.
Sylius's documentatoin about how to contribute is pretty complete and it would be awesome if we could have one. You're welcome if you want to contribute on our documentation. Day after day we work hard to improve it and all new ideas and contributions are very appreciate.
The team and me will review your work with great pleasure !

If you need help don't hesitate to ping me. I'll be happy to help you for this PR !
Willy

**Comment by a2xchip** [comment]
@willy-ahva I am preparing PR for #267, and can start this issue after it.
