### ISSUE TITLE
[Contributing] Submitting a feature request - broken link bug

### ISSUE THREAD

**Issue by a2xchip** [akeneo/pim-docs#299]
**I'm submitting a bug**

The link on [Submitting a feature request](http://docs.akeneo.com/master/contributing/feature_request.html) page is broken:

http://www.akeneo.com/forum/feature-request/

**Comment by Hocdoc** [comment]
[Done](https://github.com/akeneo/pim-docs/pull/302), fixing links just take one minute thanks to GitHub.

By the way, the new Akeneo 404-error page is really funny :-). When I have even more time than just fixing links I will build my own paper hydra...

**Comment by a2xchip** [comment]
Wow! You are very fast @Hocdoc 
Yeah i mentioned it too about 404. First time i thought that this link were broken especial to expose the beauty of Akeneos 404 page :smile: :smile:
