### ISSUE TITLE
Update job configuration in "How to create a new connector ?"

### ISSUE THREAD

**Issue by willy-ahva** [akeneo/pim-docs#30]
OLD : 
reader:    pim_base_connector.reader.doctrine.bulk_product
processor: pim_base_connector.processor.csv_serializer.product
writer:    pim_base_connector.writer.product_file

NEW : 
reader:    pim_base_connector.reader.doctrine.product
processor: pim_base_connector.processor.product_to_flat_array
writer:    pim_base_connector.writer.file.csv_product

**Comment by nidup** [comment]
@willy-ahva still useful or should be closed?

**Comment by a2xchip** [comment]
@willy-ahva Ping

**Comment by willy-ahva** [comment]
It seems that the demo bundle has been moved. I think I merged this PR yet. So we can close it.
