### ISSUE TITLE
Link to the EE edition, public readers see a 404

### ISSUE THREAD

**Issue by ronanguilloux** [akeneo/pim-docs#329]
in page http://docs.akeneo.com/latest/cookbook/product_asset/add_new_transformation.html, the link at the end of the sentence "To see how the imagemagick command is launched, you can take a look at the ImageMagickLauncher." leads to the EE source code.
Such URL require access to a private rep, so public doc reader cannot read further, So it may be helpful to precise that this link require granted access to the EE.

**Comment by solivier** [comment]
@ronanguilloux Fixed thank for the issue.
