### ISSUE TITLE
Add information about ImageMagick in our doc

### ISSUE THREAD

**Issue by LaureBro** [akeneo/pim-docs#383]
Add info about ImageMagick which is a pre-requisite for the Enterprise Edition since 1.4 version.
Update cookbook for 1.5 and 1.6 versions - for page System Requirements.

Specify that it needs to be installed only for EE.

**Comment by dnd-tyler** [comment]
@LaureBro @mickaelandrieu there is already info about ImageMagick for cookbook in 1.5 : https://docs.akeneo.com/1.5/developer_guide/installation/system_requirements/system_requirements.html.
So I think, we just have to add it into the cookbook of 1.6 and 1.7. Do you confirm that ?

**Comment by damien-carcel** [comment]
We need php-imagick extension, but also imagemagick itself.

**Comment by damien-carcel** [comment]
ImageMagick is a requirement of `php-imagick`, so in fact you cannot have the extension without the utility.
Plus extra dependencies were added since the 2.0 documentation, including ImageMagick, so I'm closing this issue.
