### ISSUE TITLE
[Cookbook] Missing informations in "How to Create a Reference Data"

### ISSUE THREAD

**Issue by JulienDotDev** [akeneo/pim-docs#412]
Hi,

It seems that many informations are missing on this page : https://docs.akeneo.com/master/cookbook/catalog_structure/creating_a_reference_data.html#how-to-create-a-reference-data

After the configuration of the reference data there is one command to check the doctrine schema and one to check the reference data but nothing about update the doctrine schema or update the database : https://docs.akeneo.com/master/cookbook/catalog_structure/creating_a_reference_data.html#configuring-the-reference-data

It looks like these insctructions are missing : 
php doctrine:schema:update --dump-sql
php app/console doctrine:schema:update --force

With only the insctructions of the cookbook, you can't make a reference data work.

Regards,

**Comment by a2xchip** [comment]
@JulienDotDev Feel free to contribute by adding specified note :+1:

**Comment by JulienDotDev** [comment]
@a2xchip Right now i'm not even able to make a reference data work so i won't push any note or instructions ^^

**Comment by a2xchip** [comment]
@JulienDotDev :smile: :smiley:

**Comment by mickaelandrieu** [comment]
It's now documented, thank for report the issue
