### ISSUE TITLE
Create a Custom Step on 1.7 Cookbook is outdated.

### ISSUE THREAD

**Issue by nei** [akeneo/pim-docs#557]
I've used this Custom Step Notification cookbook on previews version to upgrade my bundle to 1.6 and now I need to upgrade for 1.7 I've noticed that this documentation [Create-Custom-Step](https://docs.akeneo.com/1.7/cookbook/import_export/create-custom-step.html) is outdated.

Specifically the way it implements the form that still using the FormConfigurationProviderInterface.

**Comment by mickaelandrieu** [comment]
Seen with @nei, we don't need to update this item :)
