### ISSUE TITLE
Http status code documentation/implementation mismatch

### ISSUE THREAD

**Issue by pardahlman** [akeneo/pim-docs#560]
I found a discrepancy in the API documentation over at [api.akeneo.com](https://api.akeneo.com). From what I can gather, this repo contains the source code to the "normal" documentation, so I suspect this isn't the right place to report this. Sorry! Is there a dedicated (public) repo for the API docs?

The endpoint for [deleting products](https://api.akeneo.com/api-reference.html#delete_products__code_) is expected to return `200 OK` if the operation was successful (according to docs). When I use the endpoint in version 1.7.2, I get a `204 No Content` when the operation is successful.

This isn't holding me up, I just thought I'd report this so that the documentation for the new API is spotless ✨ 

Thanks!

**Comment by nidup** [comment]
Hi @pardahlman !

Thank you for your feedback! We just open sourced the repository of the api doc https://github.com/akeneo/pim-api-docs

Feel free to contribute by opening a PR on this repo! :tada:

**Comment by pardahlman** [comment]
Hello again @nidup - thanks for pointing me in the right direction! I'll see if I find the time in the coming days to help out!

**Comment by ahocquard** [comment]
Fixed in this PR. Thanks for the report :)
