### ISSUE TITLE
We should notify user who visit a deprecated version of documentation

### ISSUE THREAD

**Issue by mickaelandrieu** [akeneo/pim-docs#576]
Hello,

at this moment, only versions 1.5+ of Akeneo are actually maintained. We should warn users of old version and advise them to migrate asap.

For instance, this is what is done in Symfony project:

![capture](https://cloud.githubusercontent.com/assets/1247388/25741751/86b1c56a-318c-11e7-85e7-9e16335fef7e.PNG)

To do it, we need to rely on version value of each [documentation version](https://github.com/akeneo/pim-docs/pull/569), then we can easily display a block dynamically to inform our users :)

**Comment by pardahlman** [comment]
I agree! A common mistake for me is that I use google to find documentation (using search terms like _akeneo attribute option_) and the highest ranking match is always for 1.5. It would help me a lot in those cases if I got a gentle reminder that I'm not reading the latest docs.

**Comment by damien-carcel** [comment]
Merged, all our old documentation now display such a deprecation warning :).
