### ISSUE TITLE
Cookbook: product xml import outdated

### ISSUE THREAD

**Issue by a2xchip** [akeneo/pim-docs#604]
According to CHANGELOG 1.7 implementations of `Pim\Bundle\ImportExportBundle\JobParameters\FormConfigurationProviderInterface;` were removed and there is no such interface in code base anymore, means interface itself was removed too. But it is still used  in master `https://docs.akeneo.com/master/cookbook/import_export/product-import-from-xml-file.html` and 1.7 version of same page.

**Comment by mickaelandrieu** [comment]
Hi @a2xchip,

do you think you can "refresg" this cookbook?

Mickaël

**Comment by damien-carcel** [comment]
Closing as it has been fixed on 1.7 documentation and merged into 2.0 too.
