### ISSUE TITLE
No mention of database configuration

### ISSUE THREAD

**Issue by QwertyZW** [akeneo/pim-docs#607]
Expected a mean to provide akeneo with database information in https://github.com/akeneo/pim-docs/blob/1.7/developer_guide/installation/installation_archive.rst.inc but nothing found.

# Problem #

Command `pim:install` fails with

```
Prepare database schema (driver: doctrine/orm)
Database does not exist yet
Could not create database for connection named `akeneo_pim`
SQLSTATE[HY000] [1045] Access denied for user 'akeneo_pim'@'localhost' (using password: YES)
The command terminated with an error code: 1.

                                                 
  [Exception]                                    
  The command terminated with an error code: 1.                                             
```

# Solution  #
For those running into the same issue, a quick grep reveals

```
root@ebd12080e6b1:/var/www/pim-community-standard# grep -R "akeneo_pim" app/config/
app/config/pim_parameters.yml:    # mongodb_database: akeneo_pim
app/config/parameters.yml:    database_name: akeneo_pim
app/config/parameters.yml:    database_user: akeneo_pim
app/config/parameters.yml:    database_password: akeneo_pim
app/config/parameters.yml.dist:    database_name:     akeneo_pim
app/config/parameters.yml.dist:    database_user:     akeneo_pim
app/config/parameters.yml.dist:    database_password: akeneo_pim
```

Modify your parameters.yml as appropriate and make sure you refresh the cache after you do so `php5.6 app/console cache:clear --env=prod`

**Comment by mickaelandrieu** [comment]
Hello @QwertyZW,

if you are installing the PIM from archive, you need to create your database on your own => https://docs.akeneo.com/latest/developer_guide/installation/system_requirements/system_install_ubuntu_1604.html#mysql

Note this database configuration is suitable only for development environment and you need to update the file `parameters.yml` to match your database configuration.

Let me know if you need help :)

**Comment by QwertyZW** [comment]
I'm not asking a question. I'm provding workflow feedback.

The key issue here is that [this](https://docs.akeneo.com/1.7/developer_guide/installation/system_requirements/system_requirements.html) series of documenation does **not** mention anything about the _crucial_ relationship between the `parameters.yml` file and the database

I know that I have to create my own database @mickaelandrieu although. The documentation does not state that however. What I'm complaining about is that there is no indication by anything(neither the command nor the doc) that there's a `parameters.yml` that takes the credentials to the database. 

The general pattern I've been accustomed by other PHP tools (magento, drupal, wordpress, etc), is inputting the db details in the commandline, the script then updates the config files as appropriate. But this is only a suggestion.

**Comment by mickaelandrieu** [comment]
Well, you get a point. We are aware we need to improve the installation, regarding your feedback I can tell this workflow is not disturbing in the Symfony ecosystem and Akeneo developers must have Symfony (framework) basics.

Still we could improve the docs, are you interested to contribute?

**Comment by QwertyZW** [comment]
It is definitely a workflow anyone can get used to with proper documentation. 

You mean contribute to resolving this specific issue with the documentation? Yes, of course.

**Comment by mickaelandrieu** [comment]
Glad to hear that!

You can install and setup the documentation website using the readme: https://github.com/akeneo/pim-docs#installation

We contribute docs using the ReStructuredText syntax.

If you need help tell me, I'm here to help 👍

**Comment by mickaelandrieu** [comment]
@QwertyZW do you need help? We'd like to have you as contributor 👍

**Comment by QwertyZW** [comment]
Currently stuck here https://github.com/akeneo/pim-community-dev/issues/6222

**Comment by dnd-tyler** [comment]
Hi,
So I'll do it. 
If I weel understand, I need to add the information in the doc between parameters.yml and database ?
But when you did a composer install it's ever said `Creating the "app/config/parameters.yml" file`: it's not enough ?
So I have to add something like "the app/config/parameters.yml got some configurations about the database like name, user and password".
![pim-composer](https://user-images.githubusercontent.com/22032048/27294606-6dc5150a-551a-11e7-9a9e-d558232fabd9.png)

**Comment by damien-carcel** [comment]
Closing as #616 is merged.
