### ISSUE TITLE
Broken link in `Import and export data » Formats » Attribute data structure`

### ISSUE THREAD

**Issue by a-ast** [akeneo/pim-docs#658]
How to reproduce:

1. Go to  [Attribute data structure] (https://docs.akeneo.com/master/import_and_export_data/formats/attribute.html) page.
2. Find  a table row with text 'Must be a valid reference data code (see Reference data configuration)'. 
3. Click on the link 'Reference data configuration'

Expected: Reference data configuration
Actual result: 404 page

**Comment by damien-carcel** [comment]
Hello @a-ast.

Thank you for this issue. It is now fixed in https://github.com/akeneo/pim-docs/pull/675, and should soon be deployed on docs.akeneo.com.

Regards,
Damien
