### ISSUE TITLE
Master/2.0 documentation mismatches

### ISSUE THREAD

**Issue by TheOnlyJoey** [akeneo/pim-docs#668]
https://docs.akeneo.com/master/install_pim/installation_ce_archive.html#initializing-akeneo has references to `app/console` while the new location is `bin/console`

https://docs.akeneo.com/master/install_pim/system_requirements/system_install_ubuntu_1604.html still references PHP 5 and PHP 7.0 as experimental, while 2.0 will require PHP 7.1.

**Comment by TheOnlyJoey** [comment]
Seems fixed in #671

**Comment by damien-carcel** [comment]
Yes, we are currently updating the documentation.
Will be finished tomorrow.

Regards,
Damien
