### ISSUE TITLE
Broken URL and missing documentation

### ISSUE THREAD

**Issue by ysmnikhil** [akeneo/pim-docs#725]
Link is broken https://docs.akeneo.com/latest/import_and_export_data/ui
It's added to the bottom of page
https://docs.akeneo.com/latest/import_and_export_data/guides/create-connector.html#configure-a-job

**Comment by damien-carcel** [comment]
Hello @ysmnikhil.

Thank you for raising this issue, and sorry for the delayed answer.

This error is now fixed in the 2.0 branch, and will soon be merged in the other branches.

Documentation should be deployed last week, with this fix and some others.

Kind regard,
Damien.

**Comment by KarenMayo** [comment]
Hello @ysmnikhil, 

Documentation is updated and available now. 

Thanks, 

Regards, 
Karen
