### ISSUE TITLE
Inline code blocks should not have line breaks

### ISSUE THREAD

**Issue by tamarasaurus** [akeneo/pim-docs#747]
This is an issue in all parts of the technical docs, for example - 

![image](https://user-images.githubusercontent.com/1336344/34098032-5f673ee8-e3db-11e7-9432-061b60989f43.png)

**Comment by a-ast** [comment]
Please also stop capitalizing headers or change particular headers, e.g
![image](https://user-images.githubusercontent.com/6177375/34176008-b1fc3f0e-e4fe-11e7-8c25-902fb8ff52ec.png)

**Comment by kanduvisla** [comment]
The block-styling is because of the `table`-class that is added to `code`-tags.

**Comment by tamarasaurus** [comment]
This has been fixed.
