### ISSUE TITLE
Outdated reference in "Understanding the Product Export" version 2.*

### ISSUE THREAD

**Issue by iskanderIt** [akeneo/pim-docs#854]
Hello,
in the paragraph Product Processor there is a wrong reference to '@pim_serializer.normalizer.product' that  was renamed in '@pim_catalog.normalizer.standard.product' as stated in the CHANGELOG-1.7.md

**Comment by fitn** [comment]
Hello @iskanderIt 

Thank you a lot for this feedback. Do you want to do a PR on that subject for 1.7 documentation? :)
