### ISSUE TITLE
Unclear instructions in docs

### ISSUE THREAD

**Issue by meerestier** [akeneo/pim-docs#883]
https://docs.akeneo.com/2.2/install_pim/docker/installation_docker.html states the following, this is very unclear and could be improved for newcomers

MANDATORY FOLDERS

To accelerate the installation of the PIM dependencies, Composer cache and Yarn cache are shared between the host and the containers.

You need to be sure these folders exist on your host before launching the containers. If not, Docker will create them for you, but with root permissions, preventing the containers from accessing it. As a result, dependencies installation will fail.

**Comment by damien-carcel** [comment]
Helo @meerestier and thanks for your feedback.

We will eventually work on making the install doc better that it is now, but don't hesitate to do a pull request on this section to make it clearer, if you want too.

Regards,
Damien.

**Comment by damien-carcel** [comment]
Hello @meerestier.

The documentation has been updated starting 2.2 (current) version. You can read the new explanations here https://docs.akeneo.com/latest/install_pim/docker/installation_docker.html#mandatory-folders.

Don't forget to refresh your browser cache, the changes could not appear if you don't. Let me know what you think of it.

Regards,
Damien.
